version: 2

jobs:
  build:
    working_directory: ~/makura3.github.io
    docker:
      - image: circleci/node:8
    steps:
      - checkout
      - run: 
          name: install
          command: |
            npm install
            npm install hexo-cli -D
            npm install hexo --save
      - save_cache:
          key: makura3.github.io-blog-{{ .Branch }}
          paths:
            - ~/makura3.github.io

  test:
    docker:
      - image: circleci/node:8
    steps:
      - run: echo "* *--   skip test   -- * *"

  deploy:
    working_directory: ~/
    docker:
      - image: circleci/node:8
    steps:
      - restore_cache:
          keys:
            - makura3.github.io-blog-{{ .Branch }}
      - run:
          name: run deploy
          command: |
            git config --global user.name "makura3"
            git config --global user.email "makumaku300@gmail.com"
            git submodule init
            git submodule update
            npx hexo clean
            npx hexo generate
            npx hexo deploy

## run jobs
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
      - deploy:
          requires:
            - test
          filters:
            branches:
              ignore: master


## build taeget
##general:
##  branches:
##    ignore:
##      - master
    ##only:
    ##  - development

## skip test
##test:
##  override:
##    - echo "* *--   skip test   -- * *"

## deploy setting
##deployment:
##  deploy:
##    branch: development
##    commands:
##      - git config --global user.name "cakura3"
##      - git config --global user.email "makumaku300@gmail.com"
##      - git submodule init
##      - git submodule update
##      - hexo clean
##      - hexo generate
##      - hexo deploy