# Header
menu:
  Home: https://makura3.github.io/
  Archives: https://makura3.github.io/archives
#rss: /atom.xml

# Content
#excerpt_link: Read More
#fancybox: true

# display widgets at the bottom of index pages (pagination == 2)
index_widgets:
# - category
# - tagcloud
# - archive

# widget behavior
#archive_type: 'monthly'
#show_count: false

# Miscellaneous
google_analytics:
favicon: /favicon.png

# Social Accounts
twitter_url:
facebook_url:
instagram_url:
github_url: https://github.com/makura3/makura3.github.io

# style settings
node_sass:
  debug: false
  outputStyle: compressed
  precision: 5
  sourceComments: false
  includePaths: ['./node_modules/normalize-scss/sass/','./node_modules/reset-css/']