# Header
menu:
  Home: /
  Archives: /archives
#rss: /atom.xml

# Content
#excerpt_link: Read More
#fancybox: true

# Sidebar
#sidebar: right
#widgets:
#- category
#- tag
#- tagcloud
#- archive
#- recent_posts

# display widgets at the bottom of index pages (pagination == 2)
index_widgets:
# - category
# - tagcloud
# - archive

# widget behavior
#archive_type: 'monthly'
#show_count: false

# Miscellaneous
google_analytics:
favicon: /favicon.png

# Social Accounts
twitter_url:
facebook_url:
instagram_url:
github_url: https://github.com/makura3/makura3.github.io
