# Header
menu:
  Home: /
  profile: /profile
#rss: /atom.xml

# Content
#fancybox: true

# Miscellaneous
google_analytics: UA-117837032-1
favicon: /favicon.png

# Social Accounts
twitter_url:
facebook_url:
instagram_url:
github_url: https://github.com/makura3/makura3.github.io

# style settings
node_sass:
  debug: false
  outputStyle: compressed
  precision: 5
  sourceComments: false
  includePaths: ['./node_modules/normalize-scss/sass/','./node_modules/reset-css/']