# Header
menu:
  Home: /
  profile: /profile

rss: /atom.xml

# Content
#fancybox: true

# Miscellaneous
google_analytics: UA-117837032-1
favicon: /favicon.png
open_graph:
  thumbnail:
  fb_app_id:
  fb_admins:
  twitter_id: _makura3
  google_plus:

# Social Accounts
twitter_url: https://twitter.com/_makura3
facebook_url:
instagram_url:
github_url: https://github.com/makura3/makura3.github.io

# style settings
node_sass:
  debug: false
  outputStyle: compressed
  precision: 5
  sourceComments: false
  includePaths: ['./node_modules/normalize-scss/sass/','./node_modules/reset-css/']

autoprefixer:
  exclude:
    - '*.css'
  browsers:
    - 'last 3 versions'